### ISSUE TITLE
CI build

### ISSUE THREAD

**Issue by JeroMiya** [OSVR/OSVR-Config#10]
Create a CI build for OSVR-Config the generates binaries we can then upload publicly.

**Comment by JeroMiya** [comment]
@rpavlik helped with this and now we have a CI build. But we should probably get a build badge before we mark this issue done.

**Comment by rpavlik** [comment]
Not sure we can do build badge out of our jenkins easily.

**Comment by JeroMiya** [comment]
OK, closing for now.
