### ISSUE TITLE
Set the default maxMsBeforeVsync to 0

### ISSUE THREAD

**Issue by russell-taylor** [OSVR/OSVR-Config#35]
This is better for almost all apps and prevents reducing the amount of time available for rendering in some cases.

**Comment by JeroMiya** [comment]
I don't have a "set defaults" feature yet, though that sounds like it might be useful (maybe on a per-section basis?). One VERY important rule of editor UX: do no change something simply by opening it. If something is wrong - you can warn them and offer to fix it and/or have a "set defaults" feature, but don't fix it automatically.

**Comment by russell-taylor** [comment]
I meant just the default value that is used by the program when you run it.  If it is reading the value from an installed file, then we should be fine as soon as the new CI build completes and we can close this issue.

**Comment by JeroMiya** [comment]
Are you saying that this is the default value used by the server when the config file doesn't specify a value?

**Comment by russell-taylor** [comment]
I was saying that I modified the server configs in the OSVR-Core source to all have a value of 0 here.  It looks like the default was 3ms if there was no server file, so I'll go ahead and change that to 0 as well.
