### ISSUE TITLE
Create build/development documentation

### ISSUE THREAD

**Issue by JeroMiya** [OSVR/OSVR-Config#7]
We have a complete lack of documentation for building/developing the project. Fix.

**Comment by mebalzer** [comment]
Please do.  I am really struggling with creating a build for Android.  It seems the tools are many, and hard to keep track of and confusing.  Currently all I want to do is test an Android build on the NVIDIA Shield TV and and it has become a frustrating three day event.  I have accomplished a build of the OSVR Server Launcher, but don't know where to find the binaries.  I am assuming I have to build these as well from the OSVR-Android-Build, but this uses Cmake, Ninja and other tools I am not familiar with. Thank you for taking the time to address documentation.

**Comment by JeroMiya** [comment]
This github issue is specifically for the OSVR-Config utility's build instructions.

Speaking of which, this issue is implemented in https://github.com/OSVR/OSVR-Config/commit/60b615454e13e48afc7510c687e7a6fd801ca565
